#%RAML 1.0 DocumentationItem
title: Sales Force Account API Home
content: |
  Salesforce Account API enables developers to build applications that make use of the information from resource methods implemented within the API.

  This API contains functionality that allows developers to add, update, retreive, query and delete account information. Also, it allows for the addition and retreival of transaction information. 