#%RAML 1.0 NamedExample
value:
-
  AccountNumber: 'CD355119-A'
  Industry: 'Food & Beverage'
  Type: 'Customer-Direct'
  AccountSource: 'Partner Referral'
  AnnualRevenue: '850000000'
-
  AccountNumber: 'ZA456563-I'
  Industry: 'Retail'
  Type: 'Prospect'
  AccountSource: 'Phone Inquiry'
  AnnualRevenue: '730000000' 
