#%RAML 1.0 NamedExample
value:
  transactionID: 'b05f550d-1915-4tf'
  postedAt: 2016-02-28T16:41:41.090Z
  completedAt: 2016-02-28T16:41:41.090Z
  transactionName: 'UK Oil & Gas Transaction'
  account:
    AccountNumber: 'CD355119-A'
    Industry: 'Food & Beverage'
    Type: 'Customer-Direct'
    AccountSource: 'Partner Referral'
    AnnualRevenue: '850000000' 
